name: Run code format checks

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  run-pre-commit-checks:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.70.1
          frozen: true

      - name: Run tests
        run: pixi run -e linters linters
